name: terraform validate

on:
  workflow_call:
    inputs:
      terraform-dir:
        description: "Name of the terraform directory in repository root"
        required: true
        default: "terraform"
        type: string
      use-backend:
        description: "Use backend config during validation"
        required: false
        default: "false"
        type: string

jobs:
  ## VALIDATION
  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate-terraform
        run: |
          cd ${{ inputs.terraform-dir }}
          terraform init -backend=${{ inputs.use-backend }}
          terraform validate -no-color
      - name: setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
      - name: run tflint
        run: tflint -f compact
